package com.livepokernotes.framework.datasource.database

const val SESSION_ORDER_ASC: String = ""
const val SESSION_ORDER_DESC: String = "-"
const val SESSION_FILTER_COMMENT = "comment"
const val SESSION_FILTER_DATE_CREATED = "created_at"

const val ORDER_BY_ASC_DATE_UPDATED = SESSION_ORDER_ASC + SESSION_FILTER_DATE_CREATED
const val ORDER_BY_DESC_DATE_UPDATED = SESSION_ORDER_DESC + SESSION_FILTER_DATE_CREATED
const val ORDER_BY_ASC_COMMENT = SESSION_ORDER_ASC + SESSION_FILTER_COMMENT
const val ORDER_BY_DESC_COMMENT = SESSION_ORDER_DESC + SESSION_FILTER_COMMENT

const val SESSION_PAGINATION_PAGE_SIZE = 30

class SessionDao {
}